name: Bug反馈🐛
description: 反馈你遇到的bug
labels: ["(S1 - Need confirmation)"]

body:
  - type: markdown
    attributes:
      value: "🐛"

  - type: textarea
    id: description-of-bug
    attributes:
      label: 描述你遇到的bug
    validations:
      required: true

  - type: textarea
    id: save-file
    attributes:
      label: 上传你的存档
      description: "调试菜单 -> 信息 -> 生成最小化存档"
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 复现bug的步骤
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: |
        **If applicable**, add screenshots to help explain your problem.
        Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context"
    validations:
      required: false

  - type: textarea
    id: version
    attributes:
      label: 游戏版本
    validations:
      required: true

    
