name: 特性请求⭐️
description: 为这个项目提出一个想法
labels: ["<Suggestion / Discussion>"]

body:
  - type: markdown
    attributes:
      value: "⭐️"
  - type: textarea
    id: description
    attributes:
      label: 描述你的请求.
    validations:
      required: true

  - type: textarea
    id: description-of-solution
    attributes:
      label: 你设想中的解决方案.
    validations:
      required: true
    
